gr-dtv: use GR logging for debug messages
gnuradio/gnuradio pull request #3647
Opened 2020-07-16 03:05 UTC by sashko

Part of #3362.

2020-07-16 03:52 UTC, drmpeg commented
It's not really useful to modify this file. It was never executed and it's no longer being built. It's just there for historical purposes. It's been replaced with a pre-built file so that gr-dtv can be cross compiled. See:

https://github.com/gnuradio/gnuradio/commit/5af80cc3146a908f3d3fd4fb201f8eebe03eff1e

2020-07-16 05:58 UTC, sashko commented
> It's not really useful to modify this file. It was never executed (during runtime) and it's no longer being built. It's just there for historical purposes. It's been replaced with a pre-built file so that gr-dtv can be cross compiled. See:
> 
> [5af80cc](https://github.com/gnuradio/gnuradio/commit/5af80cc3146a908f3d3fd4fb201f8eebe03eff1e)

Understood. Let's try with something else then...

2020-11-01 19:54 UTC, willcode commented on gnuradio-runtime/lib/prefs.cc
> +    std::ostringstream msg;
msg never gets logged.

2020-12-19 00:43 UTC, marcusmueller requested changes

2020-12-19 00:43 UTC, marcusmueller commented on gnuradio-runtime/lib/prefs.cc
> +                << "' could not be opened for reading." << std::endl;
This is in the right spirit, but `msg` will have to end up in the logger, too!

2021-02-01 22:25 UTC, mbr0wn commented
@sashko We would still like to merge this. It's a small enough change, and a good one. However, the comments need to be resolved (i.e., `msg` needs to be logged), and can you please sign-off your commit (`git commit -s`). We'll close this if it doesn't get resolved, to reduce clutter in our PR queue.

2021-02-08 08:49 UTC, mbr0wn commented
Closing due to lack of action (we need to de-clutter the PR queue). Please reopen if you can update the PR. Thanks for your contribution!

2021-02-08 08:49 UTC, closed without merging