modtool: leave out bindings for python only modules
gnuradio/gnuradio pull request #3783
Opened 2020-09-29 11:05 UTC by mormj

Python-only modules were not skipping out on the binding compilation causing build errors.  This copies the breakout code previously from the swig directory

Fixes #3782

2020-09-29 11:53 UTC, drmpeg requested changes
As a test case, I'm using gr-paint which has a Python module.

In the installed file <install_dir>/lib/python3/dist-packages/paint/__init__.py, the following code is inserted.
```
# import pybind11 generated symbols into the paint namespace
try:
    from .paint_python import *
except ImportError:
    dirname, filename = os.path.split(os.path.abspath(__file__))
    __path__.append(os.path.join(dirname, "bindings"))
    from .paint_python import *
```
But that code doesn't exist, so the following error happens:
```
Executing: /usr/bin/python3.6 -u /home/re/xfer/image.py

Traceback (most recent call last):
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/paint/__init__.py", line 17, in <module>
    from .paint_python import *
ModuleNotFoundError: No module named 'paint.paint_python'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/re/xfer/image.py", line 33, in <module>
    import paint
  File "/opt/gnuradio-3.9.0git/lib/python3/dist-packages/paint/__init__.py", line 21, in <module>
    from .paint_python import *
ModuleNotFoundError: No module named 'paint.paint_python'
```

2020-09-29 11:55 UTC, drmpeg commented on gr-utils/modtool/templates/gr-newmod/python/bindings/CMakeLists.txt
> +    MESSAGE(STATUS "No C++ sources... skipping swig/")
Swig?

2020-09-29 11:59 UTC, mormj commented on gr-utils/modtool/templates/gr-newmod/python/bindings/CMakeLists.txt
> +    MESSAGE(STATUS "No C++ sources... skipping swig/")
oops.  Bad copy/paste.  fixed now.

2020-09-29 12:01 UTC, mormj commented
So the python `__init__` in 3.8 has the following comment:

```
# import swig generated symbols into the howto namespace
try:
    # this might fail if the module is python-only
    from .howto_swig import *
except ImportError:
    pass
```

Reduced the import from the python bindings to that, added the comment - this could probably be eliminated in the case there are no c++ blocks with a little work, but this should match 3.8 behavior

2020-09-29 12:38 UTC, drmpeg commented
The fix to \_\_init\_\_.py works, but if I add a C++ module after, the pybind11 modules don't get compiled because the ```No C++ sources... skipping python bindings"``` path gets taken in ```gr-paint/python/bindings/CMakeLists.txt```.

2020-09-29 19:51 UTC, mormj commented
Ok, that was an even dumber copy paste (copied the template after howto had already been replaced in my local dir) :/  Should be working now.

2020-09-30 00:07 UTC, drmpeg approved these changes
Looks good. There is a small downside. If you have a linking error, you get the old ```AttributeError: module 'paint' has no attribute 'paint_bc'``` versus a more informative ```ImportError: /opt/gnuradio-3.9.0git/lib/libgnuradio-paint.so.1.0.0git: undefined symbol: _ZN2gr3fft11fft_complexC1Eibi```.

2020-10-23 17:19 UTC, mormj commented
Yeah, I think that issue existed in the swig bindings as well because of the `pass`.  Going to go ahead and merge this and add an issue that that masking should be resolved

2020-10-23 17:20 UTC, merged