Modify template to cast Python pointer correctly
gnuradio/gnuradio pull request #3847
Opened 2020-10-14 16:05 UTC by dl1ksv

The mako template creates code fo PyObject * that must be hand edited.
For instance see the comments for qtgui widgets:

        // .def("pyqwidget",&sink_f::pyqwidget,
        //     D(sink_f,pyqwidget)
        // )
        // For the sip conversion to python to work, the widget object
        // needs to be explicitly converted to long long.
This modification does this cast for PyObject *  . So no more hand editing is needed

2020-10-14 18:52 UTC, mormj requested changes

2020-10-14 18:52 UTC, mormj commented on gr-utils/bindtool/templates/generic_python_cc.mako
> +##        .def("${fcn['name']}",
Can you please remove the comments

2020-10-14 18:52 UTC, mormj commented on gr-utils/bindtool/templates/generic_python_cc.mako
> +##        ${modvar if isfree else ""}${".def_static" if has_static and not isfree else ".def"}("${fcn['name']}",${overloaded_str}&${cls_name}::${fcn['name']},
Can you please remove the commented line since the overloading is moved up into the statement above

2020-10-14 18:53 UTC, mormj commented
Tested modtool on an OOT with overloaded methods, and it still seems to work.  Don't have a good way of testing on QT OOT that require the additional if statements in here.  @dl1ksv - do you have a public OOT I can test with?

2020-10-15 15:07 UTC, dl1ksv commented
Unneeded comments are now removed. @mormj you can use the test_case branch from
[gr_display](https://github.com/dl1ksv/gr-display)

2020-10-16 10:29 UTC, mormj commented
Tested on my machine with gr-display:
```
gr_modtool bind show_image --addl_includes /usr/include/x86_64-linux-gnu/qt5/QtGui,/usr/include/x86_64-linux-gnu/qt5,/usr/include/x86_64-linux-gnu/qt5/QtCore,/usr/include/x86_64-linux-gnu/qt5/QtWidgets,/usr/include/qwt,/usr/include/python3.8/
```
generates valid binding code 
LGTM

2020-10-16 10:30 UTC, mormj approved these changes

2020-10-20 10:20 UTC, merged