fix header_format_default access code search method
gnuradio/gnuradio pull request #3859
Opened 2020-10-17 12:52 UTC by lawchange

1.only search bits from input
2.reset d_data_reg and d_data_reg_len if access_code matched
3.fix overflow?

2020-10-19 10:40 UTC, mormj commented
@lawchange - thank you for the contribution.  This looks very similar to #3692 - can you verify whether that pull request achieves the same goal?

2020-10-19 23:31 UTC, willcode commented on gr-digital/include/gnuradio/digital/header_format_default.h
> +    size_t d_data_reg_len; //!< Length of the saved access_code
//!< Number of valid bits in data register

2020-10-19 23:31 UTC, willcode commented on gr-digital/lib/header_format_default.cc
> +                if (d_data_reg_len == d_access_code_len){
Use else?

2020-10-19 23:38 UTC, willcode requested changes
Looks good after a couple of very minor changes.

2020-10-19 23:41 UTC, willcode commented
@mormj This is a different piece of code than #3692 isn't it?

The check failed on a pybind header mismatch.

2020-10-20 09:59 UTC, mormj commented
Yes, you're right it is - made too cursory a glance.  To fix the pybind headers, since nothing was changed in the API, you can just update the hashes in the _python.cc

```
md5sum gr-digital/include/gnuradio/digital/header_format_default.h
```
replace the hash in gr-digital/python/bindings/header_format_default_python.cc

2021-01-11 15:16 UTC, mbr0wn commented
Due to lack of activity, I'll close this. Please reopen if that was an error on my part, we're certainly very happy about all contributions. If you do, please make sure formatting and DCO (sign-off) are in order. Thanks!

2021-01-11 15:16 UTC, closed without merging