qtgui: Fix QT chooser labels
gnuradio/gnuradio pull request #4046
Opened 2021-01-06 14:15 UTC by haakov

Fixes https://github.com/gnuradio/gnuradio/issues/4031

Should be tested extensively, I can't guarantee that the `value in options` assert (which is a small enhancement unrelated to the original bug) does not collide with some existing flow graphs.

2021-01-06 18:10 UTC, nickoe commented
Test of patch set so far, see https://github.com/gnuradio/gnuradio/issues/4031#issuecomment-755466301

2021-01-08 07:46 UTC, nickoe requested changes
You effectively made this more user friendly and this constraint in the docs can be removed:
"When the labels is an empty list, the options will be used as the label."

2021-01-16 15:01 UTC, mbr0wn commented
@nickoe @haakov are you two hashing this out? @nickoe if you approve the PR, I'd be inclined to merge based on my cursory understanding what's going on here.

2021-01-16 16:49 UTC, haakov commented
I'd like to make sure this PR doesn't break anything in the existing examples:
- [ ] ./gr-dtv/examples/uhd_atsc_rx.grc
- [ ] ./gr-blocks/examples/matrix_multiplexer.grc
- [ ] ./gr-digital/examples/demod/constellation_soft_decoder.grc
- [ ] ./gr-digital/examples/demod/symbol_sync_test_complex.grc
- [ ] ./gr-digital/examples/demod/symbol_sync_test_float.grc
- [ ] ./gr-channels/examples/demo_quantization.grc
- [ ] ./gr-uhd/examples/grc/uhd_msg_tune.grc
- [ ] ./gr-uhd/examples/grc/uhd_siggen_gui.grc
- [ ] ./gr-uhd/examples/grc/uhd_siggen_gui.grc
- [ ] ./gr-uhd/examples/grc/uhd_fft.grc
- [ ] ./gr-uhd/examples/grc/uhd_wbfm_receive.grc

@nickoe I don't think that sentence should be removed from the documentation, since it is still true when the List option is used

2021-01-16 20:15 UTC, duggabe reviewed
The code looks good. I currently am running maint-3.8
I will check the list of examples when I am on 3.9 again.

2021-01-18 14:07 UTC, duggabe commented
With Ubuntu 20.04.1 and GRC 3.9.0.0 I tested all 10 of the examples listed above (./gr-uhd/examples/grc/uhd_siggen_gui.grc was listed twice).
All of the choosers worked properly.
I approve this PR.

2021-01-20 11:48 UTC, merged

2021-01-20 21:55 UTC, nickoe commented
@mormj I suggest this be backported to 3.9 at least and possibly 3.8.

2021-01-20 22:59 UTC, duggabe commented
I agree. 3.8 needs it too!

2021-03-01 19:44 UTC, willcode commented
Backport PR for maint-3.8 was created, removing label.

2021-03-01 22:08 UTC, willcode commented
Added PR for backport to maint-3.9, removing label.