Adding direction to mtune in gr-uhd
gnuradio/gnuradio pull request #4171
Opened 2021-01-30 05:20 UTC by segdy

This is an additional fix for https://github.com/gnuradio/gnuradio/pull/4093 and https://github.com/gnuradio/gnuradio/pull/4091.

The `mtune` command does not take the `direction` parameter into account. I think I have pushed this change previously into my old pull request but I think it has not found its way to the new one.

So this is a trivial one and all it does is it reads out `direction` for `mtune` command and supplies it to `_update_curr_tune_req`.

Thanks everyone for https://github.com/gnuradio/gnuradio/pull/4093 and https://github.com/gnuradio/gnuradio/pull/4091 and thanks for merging!

2021-02-01 09:58 UTC, mbr0wn requested changes
Can you please:
- Fix the minor typo in the comment
- Change your git subject line to something like `uhd: Add direction to mtune`
    - Note how the line is prefixed by the name of the in-tree module
    - Even better would be if you add some text to the message itself, explaining what you can now do that you couldn't before.
  
Thanks!

2021-02-01 09:58 UTC, mbr0wn commented on gr-uhd/lib/usrp_block_impl.cc
> +                                   // messaged block direction"
```suggestion
                      pmt::PMT_NIL // Anything except "TX" or "RX" will default to the
                                   // messaged block direction
```

2021-02-01 17:53 UTC, segdy commented
> Can you please:
> 
>     * Fix the minor typo in the comment
> 
>     * Change your git subject line to something like `uhd: Add direction to mtune`
>       
>       * Note how the line is prefixed by the name of the in-tree module
>       * Even better would be if you add some text to the message itself, explaining what you can now do that you couldn't before.

Fixed and re-checked in. Hope this was OK.

2021-02-01 20:06 UTC, mbr0wn commented
@segdy Almost. I'm merging this by hand because there were two things still wrong:
- The subject line exceeded the 72 character limit, and
- The idea was that you squash the changes into a single commit (not add another one).

2021-02-01 20:06 UTC, closed without merging

2021-02-01 21:33 UTC, segdy commented
> @segdy Almost. I'm merging this by hand because there were two things still wrong:

Thank you, will keep these in mind for next time.
To make sure:

>     * The subject line exceeded the 72 character limit, and

Multiple lines are permitted though, each line 72 chars max?

>     * The idea was that you squash the changes into a single commit (not add another one).

Ok.
How would I have done this the correct way? `git commit --amend` ?
Or `git rebase`? This one is discouraged for commits that I pushed already (https://www.atlassian.com/git/tutorials/rewriting-history)

Also: the changes in `master` (like this pull request) will be re-integrated into maint-3.9 and appear in the next released 3.9 version, is this correct? (but not in maint-3.8 or earlier).

2021-02-02 18:12 UTC, mbr0wn commented
Rewriting history on branches is OK if they're not merged yet. So, rebase -i is my preferred tool.

There's no limit to how many lines you can have -- it's like documentation. More is often better!