This branch fix fftpack issue
gnuradio/gnuradio pull request #4245
Opened 2021-02-16 18:19 UTC by ChristopheSeguinot

This branch fix issue #4051 cannot import name 'fftpack' from 'numpy.fft'

2021-02-17 09:23 UTC, mbr0wn requested changes
@ChristopheSeguinot Many thanks, the fix is good. However, can you please make two changes:

- Sign-off your commit (using git commit -s, or simply appending a Signed-off-by line in your commit message)
- Change the commit subject line to something like:

`numpy: Fix fftpack references`

Ideally, you expand the git commit message with some more detail as well.

2021-02-18 11:57 UTC, mormj commented
Changes look good!

2021-02-18 11:57 UTC, mormj approved these changes

2021-02-18 11:58 UTC, merged

2021-03-01 19:31 UTC, willcode commented
Backport PR created for maint-3.8, removing tag.