gui : fix block can move outside top and left boundary
gnuradio/gnuradio pull request #4334
Opened 2021-03-08 16:37 UTC by ChristopheSeguinot

Signed-off-by: Christophe Seguinot <christophe.seguinot@univ-lille.fr>

This fixes #4178 
Tested on GR 3.8.2 
This can be backported to maint-3.8 and maint 3.9 
As compared to Derek proposal, the coordinate sanitizing is made inside `scale(coor, reverse=False):` method which is only called in https://github.com/gnuradio/gnuradio/blob/master/grc/gui/canvas/block.py#L61

2021-03-08 21:42 UTC, skoslowski commented
`Utils.scale()` is used in other places too... I'd recommend to put this in the setter for Block.coordinate (it's usually not a good idea to hide fixes like that away).

Another option to solve this would be to allow negative coordinates during a move, but on mouse release, shift all blocks back in non-negative values and adjust the viewport accordingly

2021-03-09 07:15 UTC, ChristopheSeguinot commented
Sorry not having seen Utils.scale was used eldwhere (I tested it but confused scale() and scale_scalar())

>> Another option to solve this would be to allow negative coordinates during a move, but on mouse release, shift all blocks back in non-negative values and adjust the viewport accordingly
Yes, the ideal would be to; on mouse release sanitize coordinates so that all seleted/moved blocks keep their relative position (all shifted of the same amount).  
Sanitizing individually each block as I did, when several blocks are selected/moved outside windows, they are all put on  left or top and superposing each other which is not convenient.

2021-03-16 11:06 UTC, mormj commented
@ChristopheSeguinot - do you plan to update this PR based on the feedback from @skoslowski?  I tested out the changes and they work as advertised, but it seems the current implementation could have other side effects based on the guidance re: `Utils.scale()`. 
Another thing I noticed is that when dragging a group of blocks, when one block hits the edge the other blocks keep moving and bunch up.

2021-03-16 17:26 UTC, ChristopheSeguinot commented
This PR must be updated, but I need some time to work on this and I'm quite busy at present.
 
> Another thing I noticed is that when dragging a group of blocks, when one block hits the edge the other blocks keep moving and bunch up.
Yes this is annoying and must be avoided.

2021-03-17 21:26 UTC, ChristopheSeguinot commented
I finally implement this fix inside the move_selected(self, delta_coordinate) method. 
This method is continuously fired when a block or a selection of blocks is moved (the final coordinate is not set on mouse release, but on the last mouse_pressed move ). 
The block selection is no longer allowed to go above top and left of the window. 
I saw that the "options blocks" could sometimes go left of 0 (-1 or -2 pixel probably). I Only observe this when moving the options blocks alone without understanding why. 

The fix was tested on 3.8.2,  whilst the PR applies to master. 
This can and should probably be backported to 3.8 and 3.9

2021-03-22 11:04 UTC, mormj approved these changes
Tested this out (on top of master) and it works - block are prevented from going off-canvas and don't bunch up when they hit the edge.  Thanks for the fix!

2021-03-28 20:55 UTC, skoslowski requested changes
Looking over the code changes, this should solve the issue. I only found some minor code-style nits.

2021-03-28 20:55 UTC, skoslowski commented on grc/gui/canvas/flowgraph.py
> +        delta_coordinate = (max(delta_coordinate[0],-min_x), max(delta_coordinate[1], -min_y))
```suggestion
        delta_coordinate = max(delta_coordinate[0],-min_x), max(delta_coordinate[1], -min_y)
```

2021-03-31 21:15 UTC, dkozel commented
@ChristopheSeguinot Can you make the small style tweaks that Sebastian has requested? I'd like to merge this. I can do them as a fixup if that's easiest.

2021-04-01 06:28 UTC, ChristopheSeguinot commented
It's done. 
Sorry for the delay, I'm not so familiar to Github and didn't realize it just need some click to accept Sebastien requests. 
Thanks Sebastien for cleaning my code.

2021-04-01 07:34 UTC, skoslowski approved these changes

2021-04-03 01:56 UTC, devnulling approved these changes

2021-04-06 11:34 UTC, merged