digital: packed<->unpacked: check chunk sizes, incl. NDBEBUG builds (backport to maint-3.9)
gnuradio/gnuradio pull request #4395
Opened 2021-03-15 18:16 UTC by willcode

Also, get rid of impossible asserts(), and throw exceptions instead of
assert(0)-aborting, as we now have facilities to handle failed
block::work().

Signed-off-by: Marcus Müller <mmueller@gnuradio.org>
(cherry picked from commit c5a1be2e93186df3c20ed2c0512dfd2e1ce7799e)
Signed-off-by: Jeff Long <willcode4@gmail.com>

Backport https://github.com/gnuradio/gnuradio/pull/4255

2021-03-15 19:29 UTC, willcode commented
@marcusmueller Another try to backport failed with lots of link errors on CI. Any idea what's going on?

2021-03-19 11:06 UTC, mbr0wn commented
`static constexpr` class members always cause some problems. I can never remember how to properly use them. Maybe you can make a `constexpr` class method `get_bits_per_type()` instead?

2021-03-19 13:48 UTC, willcode commented
Thanks for the clue ... `static constexpr` had some changes in C++17.

2021-03-22 10:50 UTC, mbr0wn requested changes

2021-03-22 10:50 UTC, mbr0wn commented on gr-blocks/lib/packed_to_unpacked_impl.h
> +    static constexpr unsigned int d_bits_per_type() { return (sizeof(T) * 8); }
```suggestion
    static constexpr unsigned int get_bits_per_type() { return (sizeof(T) * 8); }
```

The `d_` is to indicate non-static class members.

2021-03-22 20:37 UTC, mbr0wn approved these changes

2021-03-23 00:31 UTC, merged