gr-digital: Replace CMA Equalizer in MPSK Example
gnuradio/gnuradio pull request #4625
Opened 2021-05-16 09:38 UTC by solomonbstoner

In commit 65bd288, the `digital_cma_equalizer_cc` block was removed.
However, it is still left in the MPSK example flowgraph. This commit
replaces the deprecated cma equalizer with a linear equalizer and an
adaptive algorithm as those are indicated in the gnuradio wiki to be the
appropriate replacements. I have kept the parameters between the two
sets as similar as possible by ensuring the parameters with the same ids
have the same values.

Signed-off-by: Solomon Tan <solomonbstoner@yahoo.com.au>

2021-05-16 09:45 UTC, solomonbstoner commented
**Additional details regarding the PR** 

Closes issue #4624. 

The following parameters in the linear equalizer and adaptive algorithm were left as default as the `digital_cma_equalizer_cc` do not have these parameters.
1. `delta` = `10.0`
2. `ffactor` = `0.99`
3. `step size` = `0.0001`

The following parameters have the same value between the linear equalizer and adaptive algorithm and the cma equalizer they replace.
1. `sps`
2. `modulus`
3. `type` = `cma` (Im guessing this makes the linear equalizer behave like the cma one)
4. `num_taps` 

I am unsure what to do with the parameter from the cma equalizer that isnt present in the linear equalizer and adaptive algorithm
1. `mu`

Following the changes the flowgraph appears to execute nicely (ie no compilation or explicit runtime errors). I have limited knowledge in PSK so I am not sure how to confirm whether the example behaves as intended.

![Screenshot from 2021-05-16 17-19-34](https://user-images.githubusercontent.com/24548334/118392853-4712bc00-b66e-11eb-8b22-083722fc6f84.png)

2021-05-16 10:14 UTC, solomonbstoner commented
I need clarification about the choice of `Modulus`. 

In the [Adaptive Algorithm wiki](https://wiki.gnuradio.org/index.php/Adaptive_Algorithm), it is stated that 
> Modulus
>  
> (CMA only) Specifies the number of constellation points, e.g. for QPSK modulus = 4

However, `Modulus` is set to `1` in the deprecated CMA Equalizer block despite the fact the example constellation is qpsk. I just mirrored that value in the adaptive algorithm block. Just thought I should raise it up to whomever will evaluate this PR

2021-05-16 14:34 UTC, solomonbstoner commented
Closing this PR as Ill be working on a replacement with @duggabe. Will create another PR then

2021-05-17 05:57 UTC, solomonbstoner commented
@duugabe As of commit a337988, the flowgraph looks like this.

![Screenshot from 2021-05-17 13-54-23](https://user-images.githubusercontent.com/24548334/118438866-995be780-b717-11eb-92f0-761ab71c723d.png)

The replaced portion of the flowgraph looks like this.

![Screenshot from 2021-05-17 13-55-11](https://user-images.githubusercontent.com/24548334/118438950-b690b600-b717-11eb-95f5-ddd9eb9b0527.png)

2021-05-17 13:54 UTC, duggabe requested changes
The Adaptive Algorithm should have a Modulus=4
The modulus of 1 has been an error since the original tutorial was written 7 years ago.
If you change that, it should be good.
If you take care of the PR, I can work on the tutorial

2021-05-17 14:13 UTC, duggabe commented
I have made that change, tested it, and added a Note to the FG. It is in https://pastebin.com/SUDchv4K
That is the one I will use for the png in the tutorial

2021-05-17 15:23 UTC, solomonbstoner commented
> I have made that change, tested it, and added a Note to the FG. It is in https://pastebin.com/SUDchv4K
> That is the one I will use for the png in the tutorial

Might as well just use your flowgraph so itll be the same as in the tutorial. I believe beginners would greatly appreciate as little difference as possible between the provided example and the screenshot in the tutorial.

2021-05-17 23:40 UTC, duggabe approved these changes
LGTM

2021-05-19 14:53 UTC, merged