gr-iio: Add packetized transfer support using stream tags
gnuradio/gnuradio pull request #4711
Opened 2021-06-04 10:34 UTC by Yamakaja

This PR adds stream tagging support to the device_source and device_sink
blocks, and thus also deriviates like the fmcomms2 and pluto.

The important bits are:

* The source block now tags buffer boundaries
* When tagged_input is enabled on the device sink, it enforces that all input packet sizes match buffer_size / (1 + interpolation). 

This isn't very flexible, but can be understood as a safeguard against unexpected behavior.

(Continuation of #4684)

2021-06-22 01:19 UTC, tfcollins commented on gr-iio/grc/iio_device_sink.block.yml
> +  - id: uri
Standard gr seems to be "-   " not "   -"

2021-06-22 01:24 UTC, tfcollins commented on gr-iio/include/gnuradio/iio/device_sink.h
> +     * When not empty, samlpes are expected as "packets" and
samlpes -> samples

2021-06-22 01:51 UTC, tfcollins commented on gr-iio/lib/device_sink_impl.cc
> +            if (d_tags.size() != 1)
When you have small IIO buffers I think this may break since the gr buffers could be larger. Meaning you could get multiple tagged buffers passed.

2021-06-22 01:52 UTC, tfcollins requested changes
1. Can you remove the extra formatting as it breaks away from the standard gr (from what I can tell) and if formatting changes are required they should be in a separate commit.
2. With the restriction on packet length on TX, shouldn't the properties be named something like packetized_tag_key? Just to remove any confusion around actually expecting a length in the packet tag itself to be tunable.

2021-06-22 10:04 UTC, Yamakaja commented
V2:
* Addresses review comments *except* for the `packetized_tag_key` part, where i'm going to look for a little more input ;)
* Rebased on master

2021-06-23 13:06 UTC, Yamakaja commented
V3:
* Fixes device & pluto sink grc ymls

2021-06-25 12:35 UTC, mormj requested changes

2021-06-25 12:35 UTC, mormj commented on gr-iio/lib/device_source_impl.cc
> +        if (d_len_tag_key != pmt::PMT_NIL)
Can you please add braces around (even small) if and for loops

2021-06-26 15:22 UTC, Yamakaja commented
V4:
* Added some braces

2021-06-26 16:01 UTC, mormj approved these changes

2021-06-27 13:36 UTC, mormj commented
Looks like @tfcollins feedback was addressed - and thank you for adding the braces :)  Merging

2021-06-27 13:36 UTC, merged