Update berawgn.py
gnuradio/gnuradio pull request #4725
Opened 2021-06-05 18:08 UTC by besco1998

2021-06-05 21:19 UTC, marcusmueller requested changes

2021-06-05 21:19 UTC, marcusmueller commented on gr-digital/examples/berawgn.py
> +        return 1.0 / math.sqrt(self.const.bits_per_symbol* 10**(float(EbN0) / 10)))
There's four closing ) on this line, but only three (. So, this must be wrong.

2021-06-05 21:20 UTC, marcusmueller commented
Hi! It's not clear what the intention of this PR is, and sadly, it's syntactically wrong.

2021-06-06 01:19 UTC, willcode commented
@besco1998 - assuming this PR was a mistake. Please resubmit if needed.

2021-06-06 01:19 UTC, closed without merging