blocks: Throttle consume-only mode
gnuradio/gnuradio pull request #4793
Opened 2021-06-20 17:01 UTC by marcusmueller

When throttling a sample flow, it's not necessary to produce items at
the desired average rate - consuming them at a limited rate suffices to
slow down the processing of the whole flow graph just as well, and
avoids a copy.

2021-07-14 03:21 UTC, jasonuher requested changes
I couldn't get it to work in GRC without this:
```
diff --git a/gr-blocks/grc/blocks_throttle.block.yml b/gr-blocks/grc/blocks_throttle.block.yml
index ae31a9be2..894091156 100644
--- a/gr-blocks/grc/blocks_throttle.block.yml
+++ b/gr-blocks/grc/blocks_throttle.block.yml
@@ -35,6 +35,7 @@ outputs:
 -   domain: stream
     dtype: ${ type }
     vlen: ${ vlen }
+    optional: true
 
 asserts:
 - ${ vlen > 0 }

```

2021-07-14 06:53 UTC, marcusmueller commented
@jasonuher Ah, right. That's necessary for GRC usage! Added it.

2021-07-14 13:56 UTC, dkozel commented
I think this is a reasonable feature, though understanding how it works relies on an understanding of how GNU Radio handles data movement into/out of buffers. Do you have a specific usecase which motivated you to use a throttle in parallel with the main data flow? In GRC you can use bypass to easily remove/add a Throttle in series with dataflow. When setting up a flowgraph in Python/C++ I guess it is simpler to be able to conditionally hang a throttle off an output without affecting the rest of the connections.

2021-07-14 14:08 UTC, jacobagilbert commented
@dkozel IMO this is a good feature. Using a throttle in parallel can save a memcpy at a minimum, and there are other minor niche/in-the-weeds benefits of allowing throttling between two blocks while still allowing them share the same output buffer.

2021-07-19 11:21 UTC, mormj commented
Going ahead and merging this - but @duggabe note that the wiki documentation will need to be updated to reflect this usage.

2021-07-19 11:21 UTC, merged