Issue4765 log message conversion
gnuradio/gnuradio pull request #4810
Opened 2021-06-23 22:22 UTC by ronalddadds

This PR is related to #4765.

Filename: hier_block2_detail
 - [x] Create d_logger and d_debug_logger pointers and configure them
 - [x] Convert cout to use GR_LOG_INFO
 - [x] Remove <iostream> header
 - [x] Remove debug flag and associated if statements

Filename: qa_blocks_tags.cc
 - [x] Create d_logger and d_debug_logger pointers and configure them (for each tag)
 - [x] Convert cout to use GR_LOG_INFO
 - [x] Remove <iostream> header

Filename: polar_decoder_common.cc
 - [x] Settle on use of ostringstring (rather than printf)
 - [x] Convert cout to use GR_LOG_INFO
 - [x] Remove <iostream> header

2021-06-23 22:25 UTC, ronalddadds commented
Forced-push DCO sign-offs on 4 previous commits.

2021-07-10 17:50 UTC, ronalddadds commented
I've now run clang-format on these files, and fixed a build error from one of my commits.

2021-07-20 11:16 UTC, Yamakaja requested changes
First, thanks for your contribution - GitHub tells me this is your first PR :tada:

Some general comments:

* Make sure we're not logging more than before, see the fist comment regarding `GR_LOG_INFO`
* While technically not wrong, the use of `%s` for everything in `boost::format` irks me. I'd like to see the format specifier actually match what you're passing in ;)
* Pass `boost::format` directly when applicable, that might (?) save us an unnecessary type conversion.

2021-07-20 11:16 UTC, Yamakaja commented on gr-blocks/lib/qa_block_tags.cc
> +                               expected_tags3[i]));
`i` is unsigned

2021-07-20 11:16 UTC, Yamakaja commented on gr-blocks/lib/qa_block_tags.cc
> +    GR_LOG_INFO(logger, "qa_block_tags::t1");
Not quite the same

2021-07-20 11:16 UTC, Yamakaja commented on gr-blocks/lib/qa_block_tags.cc
> +    GR_LOG_INFO(logger, "qa_block_tags::t2");
The `qa_block_tags::t2` is already prepended by the logger

2021-07-20 11:16 UTC, Yamakaja commented on gr-fec/lib/polar_decoder_common.cc
> +        msg << row << "->" << int(bit_reverse(row, block_power())) << ":\t";
For consistency this could have been a `boost::format` aswell, but i suppose that's optional.

2021-07-20 11:16 UTC, Yamakaja commented on gr-fec/lib/polar_decoder_common.cc
> +        msg << "\n";
`GR_LOG_*` will add a newline for you.

2021-07-20 11:16 UTC, Yamakaja commented on gr-fec/lib/polar_decoder_common.cc
> +        GR_LOG_INFO(d_logger, msg.str().c_str());
Pretty sure `GR_LOG_*` can take your `std::string` directly.

2021-09-02 12:00 UTC, mormj commented
@ronalddadds - have you had a chance to see the feedback from @Yamakaja?

2021-09-19 08:13 UTC, mbr0wn requested changes
I would say all of these should either be `GR_LOG_DEBUG`, not `INFO`, or you keep them at INFO and use a debug logger.

2021-09-19 08:13 UTC, mbr0wn commented on gnuradio-runtime/lib/hier_block2_detail.cc
> +        GR_LOG_INFO(
I vote for `d_debug_logger`.

2021-09-19 08:13 UTC, mbr0wn commented on gnuradio-runtime/lib/hier_block2_detail.cc
> +        GR_LOG_INFO(d_logger,
Even when using `d_logger`, I think these should be `GR_LOG_DEBUG`.

2021-09-27 14:58 UTC, mormj commented
Closing due to inactivity - @ronalddadds - please reopen to address the review feedback.

2021-09-27 14:58 UTC, closed without merging

2021-09-29 10:37 UTC, dkozel commented
@ronalddadds We've also improved the chat server situation, if you could try re-registering it will hopefully work now.