Github CI: enable -Werror on fedora, but don't error on deprecations
gnuradio/gnuradio pull request #4917
Opened 2021-07-17 21:36 UTC by marcusmueller

This is to keep in lockstep with maint-3.9; this allows to run with
in-tree `[[deprecated]]`-marked functionality, and with current ZMQ,
which otherwise makes Fedora fail.

2021-07-19 10:50 UTC, mormj approved these changes
Great to have the Fedora warning checker match the other containers now.  Thanks @marcusmueller

2021-07-19 10:51 UTC, mormj commented
Just re-running the CI since Fedora did time out here (and the change here mostly impacts Fedora)

2021-07-19 12:05 UTC, marcusmueller commented
due to the appstream test, this needed a rebase

2021-07-19 19:17 UTC, marcusmueller commented
rebased.

2021-07-19 20:01 UTC, marcusmueller commented
Fedora keeps failing regardless of `-Wno-error=deprecated-declarations`, and I don't understand why :(

Need to build understanding.

2021-07-25 22:43 UTC, willcode commented
@marcusmueller The error is actually related to PCH, not the deprecation warnings: https://github.com/gnuradio/gnuradio/runs/3107416485?check_suite_focus=true#step:5:1319

2021-08-03 14:21 UTC, willcode approved these changes

2021-08-31 14:01 UTC, mbr0wn commented on .github/workflows/make-test.yml
> +            cxxflags: -Werror -Wno-error=invalid-pch -Wno-error=deprecated-declarations
Why add this everywhere else? It wasn't necessary before?

2021-09-18 21:41 UTC, mbr0wn requested changes

2021-09-18 21:41 UTC, mbr0wn commented on .github/workflows/make-test.yml
> +            cxxflags: -Werror -Wno-error=invalid-pch -Wno-error=deprecated-declarations
I meant to put this comment above, with Ubuntu.

2021-09-20 17:14 UTC, mbr0wn approved these changes

2021-09-20 17:14 UTC, merged