grc: Fix cpp hier param yaml template
gnuradio/gnuradio pull request #4951
Opened 2021-07-24 07:04 UTC by solomonbstoner

The following issues are fixed for the cpp hier block parameter yaml
template generation.
1. The key of the `data` dictionary containing the parameters should be
`parameters` instead of `param`.
2. Fix the yaml template for the parameter to generate `${param}`
instead of `$param` in the yaml file.

Changes made as part of the effort for #4944 .

Signed-off-by: Solomon Tan <solomonbstoner@yahoo.com.au>

2021-07-29 16:00 UTC, dl1ksv requested changes
With your fix I can generate cpp code, but the code generates 
typedef boost::shared_ptr<detectMarkSpace> detectMarkSpace_sptr;

Shouldn't we generate std::shared_ptr instead, at keast for the master branch ?

2021-07-29 16:25 UTC, haakov approved these changes
@dl1ksv The boost -> std change should probably be placed in a different PR so this one can be backported.

Changes look good to me

2021-07-30 08:58 UTC, dl1ksv commented
I agree

2021-07-30 08:58 UTC, dl1ksv approved these changes

2021-07-30 13:07 UTC, solomonbstoner commented
Thanks for reviewing, guys. Yeah, I was going with solving one problem at a time in each PR. Feels less messy to me

2021-08-04 02:12 UTC, solomonbstoner commented
Just realized that my commit was dated 1970 due to some clock error on my computer. Recommited the patch to put the date back to 2021. No change to the code that was approved

![Screenshot from 2021-08-04 10-10-41](https://user-images.githubusercontent.com/24548334/128110740-7f91208f-d080-4f92-91e1-7409df2a47c1.png)

2021-08-23 11:38 UTC, merged