gr-fft: add "shift" param to logpwrfft block
gnuradio/gnuradio pull request #5003
Opened 2021-08-13 20:18 UTC by willcode

Signed-off-by: Jeff Long <willcode4@gmail.com>

Closes https://github.com/gnuradio/gnuradio/issues/5000

2021-08-14 00:58 UTC, drmpeg requested changes

2021-08-14 00:58 UTC, drmpeg commented on gr-fft/python/fft/logpwrfft.py
> +            shift: enable re-ordering of FFT output to "natural" order
That's a confusing comment. What is the "natural" order? I would suggest that the comment be "shift: enable re-ordering of FFT output to place the zero-frequency component at the center of the spectrum"

2021-08-14 11:33 UTC, drmpeg approved these changes

2021-08-23 10:34 UTC, mormj approved these changes

2021-08-23 10:34 UTC, merged