Enforce some PEP8 formatting before build (backport to maint-3.9)
gnuradio/gnuradio pull request #5313
Opened 2021-11-04 20:03 UTC by mormj

Uses a github action to enforce PEP8 with some exceptions
Reformat all the python code to get it to pass this check

Backport of #5308  (would let it sit on master a bit before merging)

2021-11-10 12:52 UTC, marcusmueller commented on gnuradio-runtime/python/gnuradio/gr/CMakeLists.txt
> -    ${CMAKE_BINARY_DIR}/gruel/src/python
loool. yeah, that shouldn't be there. ooops...

2021-11-10 12:53 UTC, marcusmueller commented
Can we also get that check / corrector as script somewhere in-tree? That way, we could tell contributors that, hey, please run this and that on your changes.

2021-11-11 12:21 UTC, mormj commented
> Can we also get that check / corrector as script somewhere in-tree? That way, we could tell contributors that, hey, please run this and that on your changes.

Good point - just added a script in the tools/ directory that does both the modification and check

2021-12-04 01:05 UTC, willcode requested changes
Over-pepped some ordering by putting imports before some library load instruction. Might not be noticed if we're calling for the system default, but could fail on some systems.

2021-12-04 01:05 UTC, willcode commented on grc/main.py
>  gi.require_version('Gtk', '3.0')
`gi.require_version()` should be before `from gi.repository ...`

2022-01-15 00:20 UTC, merged