grc: store grc version info in metadata
gnuradio/gnuradio pull request #5553
Opened 2022-02-03 17:10 UTC by dl1ksv

---

# Pull Request Details

Saving a flowgraph does not save the grc version
as this info is not part of the schema.

This pr adds grc_version to the schema definition and
saves the grc version string when the fg is saved.

## Related Issue

Possibly
fixes #5521

## Which blocks/areas does this affect?

All grc files, works with files with and  without grc_version set.
## Testing Done

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

2022-02-09 16:07 UTC, mormj approved these changes

2022-02-09 22:30 UTC, willcode requested changes

2022-02-09 22:30 UTC, willcode commented on grc/core/FlowGraph.py
> +        data['metadata']['grc_version'] = self.parent_platform.config.version
A single assignment like
```
data['metadata'] = {
    'file_format': FLOW_GRAPH_FILE_FORMAT_VERSION,
    'grc_version': self.parent_platform.config.version
}
```
would be clearer.

2022-02-15 11:17 UTC, willcode approved these changes

2022-02-15 12:12 UTC, merged