Updated error mesage when block without a handler receives a message
gnuradio/gnuradio pull request #5961
Opened 2022-06-20 18:11 UTC by SaumyaBhushan

---
name: Updated error mesage when block without a handler receives a message
about: Provided more descriptive error message
title: ''
labels: '' [enhancement](https://github.com/gnuradio/gnuradio/labels/enhancement)
[good first issue](https://github.com/gnuradio/gnuradio/labels/good%20first%20issue)
[logging](https://github.com/gnuradio/gnuradio/labels/logging)
[Runtime](https://github.com/gnuradio/gnuradio/labels/Runtime)
assignees: '' 

---

# Pull Request Details

## Description

## Related Issue

## Which blocks/areas does this affect?

## Testing Done

## Checklist

- [ ] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [ ] I have squashed my commits to have one significant change per commit. 
- [ ] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [ ] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

2022-06-20 18:22 UTC, willcode commented
There are 2 different conditions (1) receipt of an unhandled message, and (2) filling the queue to max. This PR prints a message (as does the original) when both conditions are true. If fewer than 100 unhandled messages are sent, this warning will not be printed. What do we want the behavior to be?

2022-06-26 16:30 UTC, marcusmueller requested changes
Needs to be valid C++!

2022-06-26 16:30 UTC, marcusmueller commented on gnuradio-runtime/lib/tpb_thread_body.cc
> +                        f"{block.identifier()} received a message to port {i.first} which has no handler registered. Message discarded.");
`f"string"` is a python feature. This isn't valid C++!

2022-06-27 11:04 UTC, willcode commented
Closing, since this is not valid code. @SaumyaBhushan please make sure code runs correctly on your system, then submit another PR when ready. Thanks.

2022-06-27 11:04 UTC, closed without merging