GR 4.0: Qt GRC Feature Addition: Core Block Wiki Tab
gnuradio/gnuradio pull request #6198
Opened 2022-09-29 12:25 UTC by jholtom

GR 4.0: Qt GRC Feature Addition: Core Block Wiki Tab

## Description
In the Documentation workshop at GRCon 2022, we discussed the possibility of having GRC embed wiki.gnuradio.org for each of the core blocks rather than just linking out to it.

If a user does not have internet access/offline installation situation, the possibility of exporting the state of mediawiki at build and embedding it in the local docs for loading was proposed as an option
The tools here could enable this: https://github.com/SolidCharity/exportMediaWiki2HTML

The code used in this PR support loading from the web or directly embedding local HTML (QtWebEngine)

## Which blocks/areas does this affect?
The GRC Qt port - only affects Core blocks with wiki pages

## Testing Done
Tested on Fedora 36, KDE.  Needs to be tested more for blocks without wiki pages, or difficulty regularizing URLs for the Mediawiki path.

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [ ] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

2022-09-29 17:33 UTC, marcusmueller commented on grc/gui_qt/components/wiki_tab.py
> +# Copyright 2014-2022 Free Software Foundation, Inc.
We don't have to assign to the FSF – the copyright can remain with you, @jholtom if you want it.

2022-10-03 14:55 UTC, 777arc commented
Heck yeah dude!  And I'm glad we standardized on the label.replace(" ", "_") for the wiki page names, that shouldn't change, and we rarely (if ever) change the label of a block at this point.

2022-10-03 15:32 UTC, duggabe commented
Looks good to me.

2022-10-16 18:44 UTC, haakov commented on grc/gui_qt/components/canvas/block.py
> +            prefix = str(self.parent.app.platform.Config.wiki_block_docs_url_prefix)
Config should be lowercase (to access the instance, not the class)

2022-10-16 18:47 UTC, haakov requested changes
Awesome, thanks! This is a really useful feature :)

I pointed out a typo that must be fixed before merging

PS: Sorry about the delay!

2023-01-05 21:35 UTC, mormj commented
@haakov or @jholtom - any chance of getting the typo fixed and rebased to get this feature in the feature branch (and clear out the PR)?

2023-01-07 15:30 UTC, haakov commented
I'm traveling right now, but I can do it tomorrow 😊

2023-01-08 18:59 UTC, haakov commented
[Cherry-picked](https://github.com/gnuradio/gnuradio/commit/9831de3d4c7bb762b7c11239c0f5b04468aa2806) onto `feature-grc-qt` (fixed typo).

Closing.

2023-01-08 18:59 UTC, closed without merging