uhd: rfnoc: Add GRC binding and support for Vector IIR block
gnuradio/gnuradio pull request #6599
Opened 2023-03-22 21:59 UTC by gmeyerho

## Description
Add support for the Vector IIR RFNoC block

## Which blocks/areas does this affect?
gr-uhd

## Testing Done
Ran included example:
![image](https://user-images.githubusercontent.com/68391340/227048088-92e5c40d-74ff-4276-a479-1350c8a26a34.png)

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

2023-03-23 08:52 UTC, willcode approved these changes

2023-03-24 10:27 UTC, mbr0wn requested changes
Can you please fix the

2023-03-24 10:27 UTC, mbr0wn commented on gr-uhd/examples/grc/rfnoc_vector_iir_split.grc
> +    frequency0: freq
This change might be dependent on your other change (#6597) because if you open this GRC, gain and freq up empty.

2023-03-24 10:27 UTC, mbr0wn commented on gr-uhd/examples/grc/rfnoc_vector_iir_split.grc
> +    frequency3: 1e9
I think this is what we want:
```suggestion
    frequency: freq
```
(same for gain)

2023-03-30 13:12 UTC, mbr0wn approved these changes

2023-04-03 22:01 UTC, merged