Use pointers to pass s32fc arguments to VOLK
gnuradio/gnuradio pull request #6961
Opened 2023-11-15 16:54 UTC by argilo

**Note:** This draft PR depends on https://github.com/gnuradio/volk/pull/695 being merged, and VOLK 3.1.0 being released. This PR is ready for review now, but I'll leave it as a draft until VOLK 3.1.0 is out.

## Description

Passing `lv_32fc_t` arguments by value results in Undefined Behaviour, as explained in https://github.com/gnuradio/volk/issues/442. To avoid this, we use VOLK 3.1.0's updated API, where `lv_32fc_t` arguments are passed in using pointers.

Three of the affected `volk_32fc_s32fc_multiply_32fc` calls (all in gr-dtv) did not actually use a complex scalar, so I switched those calls to `volk_32f_s32f_multiply_32f` instead.

## Related Issue
Fixes #6300.
Fixes https://github.com/gqrx-sdr/gqrx/issues/781.

VOLK issue: https://github.com/gnuradio/volk/issues/442
VOLK PR: https://github.com/gnuradio/volk/pull/695

## Which blocks/areas does this affect?
* Frequency Xlating FIR Filter
* Multiply by Tag Value
* Multiply Const
* Multiply by Matrix
* Phase Shift
* Adaptive Algorithm
* DVB-T Reference Signals
* DVB-T2 Tone Reservation PAPR
* DVB-T2 Pilot Generator and IFFT

## Testing Done
Using docker multiarch, I tested https://github.com/gnuradio/volk/pull/695 together with this PR on the ppc64le architecture. Prior to the changes, 10 GNU Radio tests fail (due to segfaults), and afterwards all tests pass. Gqrx also runs without issue on ppc64le with the changes in place.

I also verified that GNU Radio's test suite passes when VOLK < 3.1.0 is used.

## Checklist
- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] ~~I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.~~
- [x] ~~I have added tests to cover my changes,~~ and all previous tests pass.

2023-11-15 18:27 UTC, marcusmueller requested changes
I think this is technically great, but it's a bit repetitive.
Let's have one header where there's `inline` functions like 
```c++
inline void volk_version_safe_rotator(gr_complex* out,
                                      const gr_complex* in,
                                      const gr_complex& phase_incr,
                                      gr_complex& phase,
                                      unsigned int n) {
#if VOLK_VERSION >= 030100
        volk_32fc_s32fc_x2_rotator2_32fc(out, in, &phase_incr, &d_phase, n);
#else
        volk_32fc_s32fc_x2_rotator_32fc(out, in, phase_incr, &d_phase, n);
#endif
}
```

2023-11-15 18:27 UTC, marcusmueller commented on gr-dtv/lib/dvbt2/dvbt2_pilotgenerator_cc_impl.cc
> +                                       reinterpret_cast<float*>(ofdm_fft.get_outbuf()),
:+1: for getting this straight

2023-11-15 19:15 UTC, argilo commented
> Let's have one header where there's `inline` functions

I considered that, but decided against it because several of the problematic VOLK calls are in public header files, which means that the inline functions would also have to go in public header files and would effectively become part of the GNU Radio API. Do you think it's worth doing that?

2023-11-15 19:28 UTC, willcode commented
Wouldn't hurt to move volk includes and any related logic in GR `.h` files to the impl as part of this.

If there are wrappers, putting them in a private place would be good. I'm on the fence about wrappers for this one, since there are some casts and the deref was added. It's not like a simple rename.

2023-11-15 19:29 UTC, argilo commented on gr-blocks/include/gnuradio/blocks/rotator.h
> +#include <volk/volk_version.h>
It looks like `volk.h` includes `volk_version.h` anyway, so it shouldn't make a difference. Maybe I don't need to include `volk_version.h` explicitly?

2023-11-15 19:52 UTC, argilo commented
I removed the `#include <volk/volk_version.h>` lines, since they shouldn't be necessary.

2023-11-15 19:52 UTC, argilo commented
> Wouldn't hurt to move volk includes and any related logic in GR .h files to the impl as part of this.

OK, I'll take a crack at it to see how it works out.

2023-11-15 20:12 UTC, argilo commented
> If there are wrappers, putting them in a private place would be good.

That might not be so easy, because the calls to `volk_32fc_s32fc_multiply_32fc` are spread across three modules (gr-blocks, gr-digital, gr-dtv).

There's only a single call to `volk_32fc_s32fc_x2_rotator_32fc`, so a wrapper wouldn't add much value for that case.

2023-11-15 20:23 UTC, argilo commented
I'm starting to think that that wrappers would be forced out into the public API and become a permanent part of GNU Radio, while we just need a temporary solution to last until the day GNU Radio's minimum VOLK version becomes >= 3.1.0 (at which point the `#if`s can be removed). So I'm inclined to leave this as-is, unless I've missed some more elegant solution.

2023-11-15 22:51 UTC, willcode commented
Agree with @marcusmueller - good for this PR - we can clean up places where there was already too much logic in the public header another time.

2023-11-17 14:39 UTC, marcusmueller commented
Yeah, I think this is good, following this discussion.

2023-11-17 14:43 UTC, marcusmueller commented
@argilo OK if I de-draftify this PR?

2023-11-17 15:55 UTC, argilo commented
I left this as a draft because the change only makes sense if https://github.com/gnuradio/volk/pull/695 is merged, and becomes part of a VOLK 3.1.0 release.

2023-11-29 00:46 UTC, willcode commented
Starting to get late for this one. Any news on the VOLK PR?

2023-11-29 01:55 UTC, argilo commented
VOLK has been quiet for the last few weeks. I pinged @jdemel on Matrix and will let you know if I hear anything.

2023-11-29 17:06 UTC, argilo commented
@jdemel is busy changing jobs and moving, so this will have to wait. The timing of VOLK 3.1.0 is uncertain, so I'd say carry on with the GNU Radio 3.10.9 release without this.

2023-12-01 18:20 UTC, argilo commented
Good news: https://github.com/gnuradio/volk/pull/695 was merged. :tada:

All that remains is for this to make it into a release so that the `#if VOLK_VERSION >= 030100` checks will work.

2023-12-01 18:31 UTC, jdemel approved these changes
LGTM. Also, you're really fast to notice these merges.

2023-12-05 20:47 UTC, argilo commented
VOLK 3.1.0 is now released. (Thanks @jdemel!) I verified that all GNU Radio tests still pass after updating VOLK.

2023-12-05 21:39 UTC, argilo commented
Tests also still pass on `maint-3.10` with this patch applied (with the exception of `qa_fir_filter`, which fails as expected because #6980 hasn't been backported yet).

2023-12-06 10:06 UTC, merged