grcqt: Minor Issues Fixes
gnuradio/gnuradio pull request #6976
Opened 2023-11-26 18:08 UTC by AsriFox

## Description
Fixes for minor issues with the Qt version of GRC:
- [x] Ctrl+Scroll zooms in on the top left corner. Maybe it should zoom in on where the mouse is?
- [x] Zooming with Ctrl +, Ctrl -, Ctrl 0 is not implemented
- [x] Generate fails if the flowgraph hasn't been saved
- [ ] Right clicking on an unselected block does not select it and give access to options like enable, disable, properties

Note: "Zoom in" shortcut is set to Ctrl =, because Ctrl + requires Shift to be pressed.

## Related Issue
Fixes #6957 

## Which blocks/areas does this affect?
GRC: Qt GUI

## Testing Done

## Checklist
- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

2023-11-28 18:18 UTC, haakov requested changes
Thank you for the PR! 

I only have a few suggestions :smiley:

2023-11-28 18:18 UTC, haakov commented on grc/gui_qt/components/canvas/block.py
> +        pos = view.mapFromScene(e.pos())
`e.pos()` is in block-relative coordinates, so you will have to map to scene coords before you can map to view coords

2023-11-28 18:18 UTC, haakov commented on grc/gui_qt/components/window.py
> +            shortcut="Ctrl+=",  # TODO: Keys.ZoomIn is "Ctrl++"
I think we should use Keys.ZoomIn, to stay consistent with GRC Gtk and other applications

2023-11-29 19:40 UTC, AsriFox commented
There are issues with GRC tests:
- GitHub actions fail because `pytest-qt` is not found in the container;
- some tests fail because of a [typo](https://github.com/gnuradio/gnuradio/blob/82c17682d4c0a95c0cecc94991aeb96d66dc5d23/grc/core/blocks/block.py#L62): there should be `parent_platform`, not `parent.platform`
- tests that involve `add_block_from_query` fail because the query does not produce a block; the text is typed in, but autocompletion doesn't work with qtbot's input (for some reason).

2023-12-03 18:12 UTC, haakov commented
Great! Thank you for the typo, just fixed it in the feature-grc-qt branch. I'm moving the other issues you mentioned to https://github.com/gnuradio/gnuradio/issues/6957, so we still have it once this PR is closed.

2023-12-21 17:19 UTC, haakov commented
https://github.com/gnuradio/gnuradio/blob/cfd798900fdd78beae8935ac304c083f0aaa256e/grc/gui_qt/components/flowgraph.py#L79

This should probably be set to False, since otherwise GRC will crash if you try to generate immedately after generating a new flowgraph

2023-12-21 17:19 UTC, haakov commented
Merging once that's fixed

2023-12-23 23:08 UTC, merged