Update qa_zeromq_pushpull.py with IPV6 test loopback
gnuradio/gnuradio pull request #7320
Opened 2024-05-06 15:37 UTC by sb424dat

Added test_002 with IPV6 loopback address to fix issue  "Can't connect to IPv6 host using ZMQ PULL Source #1866 "

## Description

## Related Issue

## Which blocks/areas does this affect?

## Testing Done

## Checklist

- [ ] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [ ] I have squashed my commits to have one significant change per commit. 
- [ ] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [ ] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

2024-05-06 15:47 UTC, sb424dat commented
tried fix issue #1866

2024-05-07 11:11 UTC, marcusmueller commented
Hi! Thanks for tackling this! 

Two things: you really *have* to sign-off your commits, as mentioned :) You can sign-off yours using `git commit --amend -s` and then `git push --force`. 

However, I think we need to technically adjust things, as well:

2024-05-07 11:15 UTC, marcusmueller requested changes

2024-07-17 08:14 UTC, mbr0wn commented
@sb424dat thanks for contributing, but we can't take the patch without the signoff. Since this hasn't seen activity for quite a while, I'll close it to keep the PR queue tidy. However, please reopen once you've addressed the comments and DCO signoff.

2024-07-17 08:14 UTC, closed without merging