grc: use state directory in generated python
gnuradio/gnuradio pull request #7455
Opened 2024-07-28 17:58 UTC by marcusmueller

## Description

Oversight on my side: new statedir is used for saving hier-blocks, but not for reading them

## Related Issue

main version of maint-3.10 #7454

## Which blocks/areas does this affect?

GRC

## Testing Done

Manual

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

2024-07-28 21:51 UTC, willcode commented
It sounds like this one is worth another release? Or does the problem hit only under certain conditions?

2024-07-28 22:19 UTC, argilo commented
If `.grc_gnuradio` exists but not `.local/state/gnuradio`, then I get the following error:

```
Traceback (most recent call last):
  File "/home/argilo/prefix_310/src/gr-ieee-80211/examples/wifi_loopback.py", line 24, in get_state_directory
    log.warn(f"Found persistent state path '{newpath}', but file does not exist. " +
    ^^^
NameError: name 'log' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/argilo/prefix_310/src/gr-ieee-80211/examples/wifi_loopback.py", line 47, in <module>
    sys.path.append(os.environ.get('GRC_HIER_PATH', get_state_directory()))
                                                    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/argilo/prefix_310/src/gr-ieee-80211/examples/wifi_loopback.py", line 33, in get_state_directory
    log.warn("Could not retrieve GNU Radio persistent state directory from GNU Radio." +
    ^^^
NameError: name 'log' is not defined
```

2024-07-28 22:27 UTC, willcode commented
@argilo is that with the PR, or is that why we need the PR?

2024-07-28 22:28 UTC, argilo commented
It's a bug in this PR.

2024-07-28 22:36 UTC, argilo commented on grc/core/generator/top_block.py
> +                        log.warn("Could not retrieve GNU Radio persistent state directory from GNU Radio." +
```suggestion
                        log.warn("Could not retrieve GNU Radio persistent state directory from GNU Radio. " +
```

2024-07-28 22:40 UTC, argilo commented on grc/core/generator/top_block.py
> +                                     f"files to '{newpath}'.")
```suggestion
                                     f"files to '{xdgcand}'.")
```

2024-07-28 22:47 UTC, argilo commented on grc/core/generator/top_block.py
> +                                     f"files to '{newpath}'.")
This same bug is also present in two places in `main.py`.

2024-07-28 22:58 UTC, argilo commented on grc/main.py
> +    oldpath = os.path.expanduser("~/.grc_gnuradio")
Is this correct? Only compiled hierarchical blocks were stored in `~/.grc_gnuradio`; `grc.conf` and `grc_qt.conf` were in `~/.gnuradio`.

2024-07-29 00:17 UTC, argilo commented on grc/main.py
> +    oldpath = os.path.expanduser("~/.grc_gnuradio")
Never mind; I see that there's a separate `get_config_file_path` function for the configuration files.

2024-08-11 16:04 UTC, dl1ksv requested changes
If the state directory exists, everything works fine.

2024-08-11 16:04 UTC, dl1ksv commented on grc/core/generator/top_block.py
> +                            log.warn(f"Found persistent state path '{newpath}', but file does not exist. " +
replace warn by warning as warn is depreceated

2024-08-11 16:04 UTC, dl1ksv commented on grc/core/generator/top_block.py
> +
add
import logging as log

2024-09-22 10:18 UTC, dl1ksv commented
This pr should be applied. Otherwise we can generate hier blocks and use them in defining flowgraphs, but the flowgraphs fail to execute.
The fg's only execute if you copy the corresponding *.py file from ~/.local/state/gnuradio to ~/.grc_gnuradio

2024-09-23 18:08 UTC, merged

2024-09-23 18:11 UTC, willcode commented
Backport note: maint-3.10 PR is already queued up.

2024-09-23 18:17 UTC, argilo commented
This is an improvement, but there were still several bugs present in this PR. We should probably open up an issue for those.