Fixed: added gr_modtool help command that should work exactly like gr_modtool --help. (issue solved #7310)
gnuradio/gnuradio pull request #7571
Opened 2024-12-19 18:46 UTC by Mindslayer001

## Description

This pull request introduces a new `gr_modtool help` command that functions equivalently to `gr_modtool --help`. This addition improves consistency and user experience by integrating the help functionality into the `gr_modtool` CLI in a more intuitive way. The implementation uses the `click` library and the `subprocess` module to execute the existing `gr_modtool --help` command and display its output.

This change resolves issue #7310.

---

## Related Issue

Fixes #7310.

---

## Which blocks/areas does this affect?

This change affects the `gr-modtool` CLI utility, specifically by adding a new command (`gr_modtool help`). It does not impact core functionality but enhances the usability of the CLI.

---

## Testing Done
- Automated tests were executed during the build process from the modified source code, and all test cases passed successfully.
- Manual testing was performed to ensure the following:
  1. The `gr_modtool help` command outputs the same content as `gr_modtool --help`.
  2. Errors are correctly handled, and appropriate error messages are displayed when the `gr_modtool --help` command fails.
  3. The `help.py` script integrates seamlessly with the `gr-modtool` build system.

- Testing Environment:
  - Operating System: Linux (Ubuntu 22.04)
  - Python Version: Python 3.x
  - GNU Radio version: Main branch, built from source.

---

## Checklist

- [x] I have read the [[CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md)](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit.  
- [x] I [[have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed).  
- [x] My code follows the code style of this project. See [[GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md)](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).  
- [x] I have updated [[the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation)](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.  
- [x] I have added tests to cover my changes, and all previous tests pass.

2024-12-20 13:01 UTC, marcusmueller requested changes

2024-12-20 13:01 UTC, marcusmueller commented on gr-utils/modtool/cli/help.py
> +            ["gr_modtool", "--help"],
that only works if `gr_modtool` is in the `$PATH` (`%path%` on windows); that's often not the case in practice!

Would it be possible to use `click.get_current_context().get_help()`? or `get_current_context().parent.get_help()`?

2024-12-20 13:03 UTC, marcusmueller commented
Hi! You still need to sign your commit! You had incorrectly ticked that checkbox, I had to revert that.

Review starts with the commit message: your commit message subject is too long, it got broken into two lines.

I'd probably rephrase the commit message to be something like

```text
modtool: add help command  that does the same as --help

This addresses Github issue gnuradio#7310. 
```

2024-12-21 01:56 UTC, Mindslayer001 commented
Hi @marcusmueller,

Thank you for the feedback! I've addressed your comments:
1. Updated the copyright attribution and removed the reference to the Free Software Foundation.
2. Replaced the `subprocess` call with `click.get_current_context().get_help()` to ensure the help command works seamlessly, even if `gr_modtool` isn't in `$PATH`.
3. Signed my commit and revised the commit message for clarity and compliance with guidelines.

Let me know if there are any other changes needed.

Best regards,  
@Mindslayer001

2024-12-22 18:27 UTC, Mindslayer001 commented
Hi @marcusmueller , I completed all  the change you mentioned. Please review the changed pr.

2024-12-24 03:06 UTC, closed without merging