GRC Qt: Prevent redundant undo actions
gnuradio/gnuradio pull request #7613
Opened 2024-12-30 19:36 UTC by Sahil-u07

## Description
Fixes the issue where two undo actions were added when moving blocks in GRC Qt. This occurred because an empty undo action was being added if the block was deselected after moving it.

## Related Issue
Fixes #7611  

## Which blocks/areas does this affect?
- Affects the **MoveAction** functionality in the **undoable_actions.py** file.
- This fix affects the undo/redo behavior in the GRC Qt interface, specifically preventing redundant actions from being added to the undo stack when blocks are moved.

## Testing Done
- Tested by moving blocks in the GRC Qt interface, deselecting the blocks, and using Ctrl+Z to undo the action.
- Verified that only one undo action is added, and that it correctly reverts the block movement.

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit.
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed).
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

2024-12-30 19:48 UTC, Sahil-u07 commented
@ThomasHabets  please review the changes. The DCO check has passed and the commit has been amended.

2024-12-30 19:49 UTC, Sahil-u07 commented
@haakov please review the changes. The DCO check has passed and the commit has been amended.

2024-12-30 20:22 UTC, marcusmueller requested changes

2024-12-30 20:22 UTC, marcusmueller commented on grc/gui_qt/components/undoable_actions.py
> +
Please avoid adding unrelated line additions. CI might complain about an extra empty line, anyways

2024-12-30 20:27 UTC, marcusmueller commented
Please fix your commit message; ours are generally formatted:

```text
area: summary

More extensive description
```

In your case, something like 
```text
GRC Qt: Prevent redundant undo actions in MoveAction

It's not clear where the empty move action comes from, but we should not insert empty actions into the undo history in any case.
```

2024-12-30 22:54 UTC, haakov commented
@Sahil-u07 Thank you for taking this on!

First of all, your fix works, so that's great :)
But we shouldn't really have to handle Move actions with zero diffs, so I'd love to see a change in this pull request that fixes the root cause of this issue.

I tried placing a breakpoint here
https://github.com/gnuradio/gnuradio/blob/d6badf773fb98e973f274b1cb0dcbcc005e4d748/grc/gui_qt/components/undoable_actions.py#L64

and reproducing the bug. It looks like an `itemMoved` signal is emitted here, from `FlowgraphScene::mouseReleaseEvent()`

https://github.com/gnuradio/gnuradio/blob/d6badf773fb98e973f274b1cb0dcbcc005e4d748/grc/gui_qt/components/canvas/flowgraph.py#L333-L334

I believe `self.moving_blocks` should only be True _while_ we're actually holding the mouse button down and moving a block. Maybe adding `self.moving_blocks = False` between the following lines would help?

https://github.com/gnuradio/gnuradio/blob/d6badf773fb98e973f274b1cb0dcbcc005e4d748/grc/gui_qt/components/canvas/flowgraph.py#L343-L344

PS: Also, I agree with @marcusmueller's comments :)

2024-12-31 09:50 UTC, Sahil-u07 commented
Hi @haakov 

Thank you for the detailed feedback! I'm glad the fix works. I understand the root cause of the issue now, and I agree that we shouldn't have to handle move actions with zero diffs.

I'll proceed with adding `self.moving_blocks = False` between `self.mousePressed = False` and `super(FlowgraphScene, self).mouseReleaseEvent(event)` in `FlowgraphScene::mouseReleaseEvent()`. This should prevent unnecessary `itemMoved `signals from being emitted.

I'll update the PR soon with these changes.

Thanks again for your help!

2024-12-31 14:35 UTC, Sahil-u07 commented on grc/gui_qt/components/undoable_actions.py
Hi @marcusmueller ,

Thank you for the feedback! I've removed the extra empty line in the undo() method as requested.

This is my first contribution to open source, and I’m really excited to be part of the project. Please let me know if there’s anything else I can improve.

Thanks again!

2025-01-03 12:58 UTC, willcode commented
Was the null MoveAction due to moving_blocks not being reset? Do we need the check in MoveAction() now?

2025-01-06 09:14 UTC, haakov commented
@Sahil-u07 Thank you for updating the PR! 

I agree with @willcode, you can remove the check in `MoveAction.__init__()`. That way, if a similar problem with "void" MoveActions shows up again, we'll know about it.

The only thing remaining after that is squashing your commits into a single commit, and this PR should be ready for merge

2025-01-06 09:15 UTC, haakov requested changes

2025-01-06 09:15 UTC, haakov commented on grc/gui_qt/components/undoable_actions.py
> +        # Prevent empty undo actions if the block hasn't moved
Remove this, as mentioned in my other comment :)

2025-01-22 12:30 UTC, haakov commented
@Sahil-u07 let us know if you have questions on how to squash the PR :)

2025-01-22 13:40 UTC, willcode commented
> @Sahil-u07 let us know if you have questions on how to squash the PR :)

And remove the check before squashing, as mentioned above.

2025-02-03 12:02 UTC, willcode commented
Included in #7673

2025-02-03 12:02 UTC, closed without merging